import {
  CalculationParameter,
  CalculationRule,
  CalculationStepTrace,
  CalculationVariable,
  Department,
  Branch,
  HREmployee,
  PayrollCalculationSnapshot,
  RuleStatus,
  TaxBracket,
  RuleVersion,
  AuditLogRecord,
} from '../types.js';

class InMemoryDB {
  public variables: CalculationVariable[] = [];
  public parameters: CalculationParameter[] = [];
  public rules: CalculationRule[] = [];
  public taxBrackets: TaxBracket[] = [];
  public snapshots: PayrollCalculationSnapshot[] = [];
  public employees: HREmployee[] = [];
  public departments: Department[] = [];
  public branches: Branch[] = [];
  public auditLogs: AuditLogRecord[] = [];

  constructor() {
    this.seedDefaults();
  }

  public seedDefaults() {
    // 1. Calculation Variables with System Source Mappings
    this.variables = [
      {
        id: 'var_1',
        code: 'BASIC_SALARY',
        name_ar: 'الراتب الأساسي',
        name_en: 'Basic Salary',
        category: 'INPUT',
        data_type: 'CURRENCY',
        description_ar: 'الراتب الاساسي للموظف المحدد في عقد العمل',
        description_en: 'Base contractual monthly salary of employee',
        is_system: true,
        default_value: 1200000,
        source_type: 'EMPLOYEE_PROFILE',
        source_mapping: {
          table: 'hr_employees',
          column: 'basic_salary',
          description: 'Loaded directly from HR Employee Contract Record',
        },
        source_table: 'hr_employees',
        source_column: 'basic_salary',
        is_input: true,
        status: 'ACTIVE',
      },
      {
        id: 'var_2',
        code: 'TOTAL_ALLOWANCES',
        name_ar: 'إجمالي المخصصات والبدلات',
        name_en: 'Total Allowances',
        category: 'INPUT',
        data_type: 'CURRENCY',
        description_ar: 'مجموع المخصصات الثابتة (سكن، نقل، معيشة، طعام، مهنة)',
        description_en: 'Sum of all monthly allowances (housing, transport, living, food)',
        is_system: true,
        default_value: 300000,
        source_type: 'CALCULATED_AGGREGATE',
        source_mapping: {
          formula_expression: 'housing + transport + living + food + other',
          description: 'Calculated dynamically from active employee allowance profile',
        },
        source_table: 'hr_employee_allowances',
        is_input: true,
        status: 'ACTIVE',
      },
      {
        id: 'var_3',
        code: 'GROSS_SALARY',
        name_ar: 'الراتب الإجمالي (الأجر الإجمالي)',
        name_en: 'Gross Salary',
        category: 'INTERMEDIATE',
        data_type: 'CURRENCY',
        description_ar: 'مجموع الراتب الأساسي والمخصصات الخاضعة',
        description_en: 'Sum of basic salary and all applicable allowances',
        is_system: true,
        source_type: 'CALCULATED_AGGREGATE',
        source_mapping: {
          formula_expression: 'BASIC_SALARY + TOTAL_ALLOWANCES',
          description: 'Calculated in Level 1 of Rules Engine',
        },
        status: 'ACTIVE',
      },
      {
        id: 'var_4',
        code: 'SOCIAL_SECURITY_BASE',
        name_ar: 'أجر الاشتراك الخاضع للضمان',
        name_en: 'Social Security Contribution Base',
        category: 'INTERMEDIATE',
        data_type: 'CURRENCY',
        description_ar: 'الوعاء المعتمد لحساب الضمان بعد تطبيق الحدود الدنيا والعليا',
        description_en: 'Applicable salary base after applying min and max caps',
        is_system: true,
        source_type: 'COMPANY_POLICY',
        source_mapping: {
          parameter_code: 'SS_MIN_BASE / SS_MAX_BASE',
          description: 'Governed by Social Security statutory floor and ceiling',
        },
        status: 'ACTIVE',
      },
      {
        id: 'var_5',
        code: 'EMPLOYEE_SOCIAL_SECURITY',
        name_ar: 'حصة الموظف من الضمان الاجتماعي',
        name_en: 'Employee Social Security Contribution',
        category: 'OUTPUT',
        data_type: 'CURRENCY',
        description_ar: 'نسبة الاستقطاع الشهري من راتب الموظف للضمان',
        description_en: 'Monthly social security deduction from employee salary',
        is_system: true,
        source_type: 'TAX_TABLE',
        source_mapping: {
          parameter_code: 'SS_EMPLOYEE_RATE',
          description: 'Derived from active statutory employee contribution rate (5%)',
        },
        status: 'ACTIVE',
      },
      {
        id: 'var_6',
        code: 'EMPLOYER_SOCIAL_SECURITY',
        name_ar: 'مساهمة جهة العمل في الضمان',
        name_en: 'Employer Social Security Contribution',
        category: 'OUTPUT',
        data_type: 'CURRENCY',
        description_ar: 'حصة صاحب العمل المدفوعة لصندوق التقاعد والضمان',
        description_en: 'Employer contribution payable to social security fund',
        is_system: true,
        source_type: 'TAX_TABLE',
        source_mapping: {
          parameter_code: 'SS_EMPLOYER_RATE',
          description: 'Derived from active employer contribution rate (12%)',
        },
        status: 'ACTIVE',
      },
      {
        id: 'var_7',
        code: 'TAX_EXEMPTION',
        name_ar: 'الإعفاءات الضريبية القانونية',
        name_en: 'Total Tax Exemptions',
        category: 'INTERMEDIATE',
        data_type: 'CURRENCY',
        description_ar: 'مجموع الإعفاء الشخصي، إعفاء الزوجة، إعفاء الأبناء، وحصة الضمان',
        description_en: 'Sum of personal, family, dependents exemptions and allowable SS deduction',
        is_system: true,
        source_type: 'TAX_TABLE',
        source_mapping: {
          description: 'Aggregated legal tax allowances defined in Law No. 113',
        },
        status: 'ACTIVE',
      },
      {
        id: 'var_8',
        code: 'TAXABLE_INCOME',
        name_ar: 'الدخل الخاضع لضريبة الدخل',
        name_en: 'Taxable Income Base',
        category: 'INTERMEDIATE',
        data_type: 'CURRENCY',
        description_ar: 'الدخل الإجمالي بعد طرح الاستقطاعات والإعفاءات المسموحة',
        description_en: 'Net taxable income base subject to progressive tax brackets',
        is_system: true,
        source_type: 'CALCULATED_AGGREGATE',
        status: 'ACTIVE',
      },
      {
        id: 'var_9',
        code: 'DEPENDENTS_COUNT',
        name_ar: 'عدد المعالين / الأطفال',
        name_en: 'Dependents Count',
        category: 'INPUT',
        data_type: 'NUMBER',
        description_ar: 'عدد أفراد العائلة أو الأطفال المشمولين بالإعفاء الضريبي',
        description_en: 'Number of eligible family dependents for tax relief',
        is_system: true,
        default_value: 2,
        source_type: 'EMPLOYEE_PROFILE',
        source_mapping: {
          table: 'hr_employees',
          column: 'dependents_count',
          description: 'Read dynamically from employee family profile in HRMS',
        },
        source_table: 'hr_employees',
        source_column: 'dependents_count',
        is_input: true,
        status: 'ACTIVE',
      },
      {
        id: 'var_10',
        code: 'TAX_AMOUNT',
        name_ar: 'مبلغ ضريبة الدخل المستحقة',
        name_en: 'Income Tax Amount',
        category: 'OUTPUT',
        data_type: 'CURRENCY',
        description_ar: 'الضريبة المستقطعة شهرياً على الدخل الخاضع للضريبة',
        description_en: 'Calculated progressive income tax deduction for the month',
        is_system: true,
        source_type: 'TAX_TABLE',
        source_mapping: {
          table: 'tax_brackets',
          description: 'Computed across active progressive tax tiers',
        },
        status: 'ACTIVE',
      },
      {
        id: 'var_11',
        code: 'TOTAL_DEDUCTIONS',
        name_ar: 'إجمالي الاستقطاعات من الراتب',
        name_en: 'Total Payroll Deductions',
        category: 'OUTPUT',
        data_type: 'CURRENCY',
        description_ar: 'مجموع استقطاع الضمان الاجتماعي وضريبة الدخل وأي استقطاعات أخرى',
        description_en: 'Sum of employee social security, income tax, and other deductions',
        is_system: true,
        source_type: 'CALCULATED_AGGREGATE',
        status: 'ACTIVE',
      },
      {
        id: 'var_12',
        code: 'NET_SALARY',
        name_ar: 'صافي الراتب المستحق للموظف',
        name_en: 'Net Payable Salary',
        category: 'OUTPUT',
        data_type: 'CURRENCY',
        description_ar: 'المبلغ النهائي المحول إلى حساب الموظف المصرفي',
        description_en: 'Final net disbursement amount payable to employee bank account',
        is_system: true,
        source_type: 'CALCULATED_AGGREGATE',
        status: 'ACTIVE',
      },
      {
        id: 'var_13',
        code: 'ALLOWABLE_DEDUCTIONS',
        name_ar: 'الاستقطاعات المسموح خصمها ضريبياً',
        name_en: 'Allowable Tax Deductions',
        category: 'INTERMEDIATE',
        data_type: 'CURRENCY',
        description_ar: 'المبالغ المسموح قانونياً استبعادها قبل احتساب الضريبة',
        description_en: 'Pre-tax allowable deductions such as employee social security',
        is_system: false,
        source_type: 'COMPANY_POLICY',
        status: 'ACTIVE',
      },
      {
        id: 'var_14',
        code: 'SENIORITY_BONUS',
        name_ar: 'مكافأة الأقدمية وسنوات الخدمة',
        name_en: 'Seniority & Service Allowance',
        category: 'INPUT',
        data_type: 'CURRENCY',
        description_ar: 'مكافأة سنوية تضاف للراتب بناءً على سنوات خدمة الموظف في المؤسسة',
        description_en: 'Seniority increment mapped from HR hire date tenure tier',
        is_system: false,
        default_value: 75000,
        source_type: 'EMPLOYEE_PROFILE',
        source_mapping: {
          table: 'hr_employees',
          column: 'hire_date',
          lookup_key: 'TENURE_TIER_IQD',
          description: 'Dynamically resolved from employee hire date duration',
        },
        source_table: 'hr_employees',
        source_column: 'hire_date',
        is_input: true,
        status: 'ACTIVE',
      },
      {
        id: 'var_15',
        code: 'OVERTIME_HOURS',
        name_ar: 'ساعات العمل الإضافي المعتمدة',
        name_en: 'Approved Overtime Hours',
        category: 'INPUT',
        data_type: 'NUMBER',
        description_ar: 'عدد ساعات العمل الإضافي المعتمدة من مدير القسم في نظام الحضور',
        description_en: 'Approved monthly overtime hours from biometric attendance bridge',
        is_system: false,
        default_value: 12,
        source_type: 'SQL_LOOKUP',
        source_mapping: {
          sql_query: 'SELECT SUM(overtime_hours) FROM employee_attendance WHERE employee_id = :employee_id AND period = :calculation_date',
          description: 'Queried safely via parameterized SQL from attendance bridge',
        },
        is_input: true,
        status: 'ACTIVE',
      },
    ];

    // 2. Calculation Parameters (Dynamic Values - not hardcoded in code!)
    this.parameters = [
      {
        id: 'param_1',
        code: 'SS_EMPLOYEE_RATE',
        name_ar: 'نسبة اشتراك الموظف في الضمان',
        name_en: 'Employee SS Contribution Rate',
        value: 5.0,
        unit: '%',
        effective_from: '2026-01-01',
        effective_to: null,
        description_ar: 'النسبة المستقطعة من أجر اشتراك الموظف (قابلة للتعديل حسب القانون)',
        description_en: 'Percentage deducted from employee contribution base',
        status: 'ACTIVE',
      },
      {
        id: 'param_2',
        code: 'SS_EMPLOYER_RATE',
        name_ar: 'نسبة مساهمة صاحب العمل في الضمان',
        name_en: 'Employer SS Contribution Rate',
        value: 12.0,
        unit: '%',
        effective_from: '2026-01-01',
        effective_to: null,
        description_ar: 'النسبة التي يتحملها صاحب العمل لصندوق التقاعد والضمان',
        description_en: 'Percentage contributed by employer to social security',
        status: 'ACTIVE',
      },
      {
        id: 'param_3',
        code: 'SS_MIN_BASE',
        name_ar: 'الحد الأدنى لوعاء اشتراك الضمان',
        name_en: 'Min Social Security Base Cap',
        value: 350000,
        unit: 'IQD',
        effective_from: '2026-01-01',
        effective_to: null,
        description_ar: 'أدنى راتب يعتمد للاشتراك بالضمان الاجتماعي',
        description_en: 'Minimum monthly salary floor for social security calculations',
        status: 'ACTIVE',
      },
      {
        id: 'param_4',
        code: 'SS_MAX_BASE',
        name_ar: 'الحد الأعلى لوعاء اشتراك الضمان',
        name_en: 'Max Social Security Base Cap',
        value: 5000000,
        unit: 'IQD',
        effective_from: '2026-01-01',
        effective_to: null,
        description_ar: 'أعلى سقف معتمد لوعاء الاشتراك الخاضع للضمان (0 يعني لا يوجد سقف)',
        description_en: 'Maximum monthly salary ceiling cap for social security',
        status: 'ACTIVE',
      },
      {
        id: 'param_5',
        code: 'TAX_PERSONAL_EXEMPTION_MONTHLY',
        name_ar: 'الإعفاء الشخصي الشهري للمكلف',
        name_en: 'Monthly Personal Tax Exemption',
        value: 208333.33, // approx 2,500,000 yearly / 12
        unit: 'IQD',
        effective_from: '2026-01-01',
        effective_to: null,
        description_ar: 'الإعفاء الضريبي الشهري الممنوح للموظف كإعفاء أساسي',
        description_en: 'Standard monthly personal statutory allowance for taxpayer',
        status: 'ACTIVE',
      },
      {
        id: 'param_6',
        code: 'TAX_SPOUSE_EXEMPTION_MONTHLY',
        name_ar: 'إعفاء الزوجة الشهري',
        name_en: 'Monthly Spouse Exemption',
        value: 166666.67, // approx 2,000,000 yearly / 12
        unit: 'IQD',
        effective_from: '2026-01-01',
        effective_to: null,
        description_ar: 'الإعفاء الضريبي الإضافي للمتزوج إذا كانت الزوجة ربة بيت',
        description_en: 'Additional monthly spousal tax relief',
        status: 'ACTIVE',
      },
      {
        id: 'param_7',
        code: 'TAX_DEPENDENT_EXEMPTION_MONTHLY',
        name_ar: 'إعفاء الطفل / المعال الشهري',
        name_en: 'Monthly Per-Child Exemption',
        value: 41666.67, // approx 500,000 yearly / 12
        unit: 'IQD',
        effective_from: '2026-01-01',
        effective_to: null,
        description_ar: 'إعفاء عن كل طفل أو معال قانوني مستحق',
        description_en: 'Monthly statutory tax exemption per eligible child or dependent',
        status: 'ACTIVE',
      },
    ];

    // 3. Tax Brackets (Version 1 - Progressive brackets)
    this.taxBrackets = [
      {
        id: 'bracket_1',
        rule_version_id: 'ver_tax_1',
        bracket_order: 1,
        name_ar: 'الشريحة الأولى (معفاة / شريحة البداية)',
        name_en: 'Bracket 1 (First Tier)',
        min_income: 0,
        max_income: 250000,
        tax_rate: 3.0,
        fixed_tax: 0,
        effective_from: '2026-01-01',
        effective_to: null,
        status: 'ACTIVE',
      },
      {
        id: 'bracket_2',
        rule_version_id: 'ver_tax_1',
        bracket_order: 2,
        name_ar: 'الشريحة الثانية (المتوسطة)',
        name_en: 'Bracket 2 (Middle Tier)',
        min_income: 250000,
        max_income: 500000,
        tax_rate: 5.0,
        fixed_tax: 0,
        effective_from: '2026-01-01',
        effective_to: null,
        status: 'ACTIVE',
      },
      {
        id: 'bracket_3',
        rule_version_id: 'ver_tax_1',
        bracket_order: 3,
        name_ar: 'الشريحة الثالثة (فوق المتوسطة)',
        name_en: 'Bracket 3 (Upper Middle Tier)',
        min_income: 500000,
        max_income: 1000000,
        tax_rate: 10.0,
        fixed_tax: 0,
        effective_from: '2026-01-01',
        effective_to: null,
        status: 'ACTIVE',
      },
      {
        id: 'bracket_4',
        rule_version_id: 'ver_tax_1',
        bracket_order: 4,
        name_ar: 'الشريحة الرابعة (الأعلى)',
        name_en: 'Bracket 4 (Top Tier)',
        min_income: 1000000,
        max_income: null, // Unlimited
        tax_rate: 15.0,
        fixed_tax: 0,
        effective_from: '2026-01-01',
        effective_to: null,
        status: 'ACTIVE',
      },
    ];

    // 4. Calculation Rules (Dynamic Rules Engine Registry)
    this.rules = [
      {
        id: 'rule_gross_salary',
        code: 'GROSS_SALARY',
        category: 'GENERAL_PAYROLL',
        name_ar: 'حساب الراتب الإجمالي',
        name_en: 'Gross Salary Calculation',
        rule_type: 'FORMULA',
        description_ar: 'جمع الراتب الأساسي وإجمالي البدلات والمخصصات الشهرية',
        description_en: 'Calculate total gross earnings: BASIC_SALARY + TOTAL_ALLOWANCES',
        execution_order: 10,
        output_variable: 'GROSS_SALARY',
        dependencies: ['BASIC_SALARY', 'TOTAL_ALLOWANCES'],
        active_version_id: 'ver_gross_2',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_gross_1',
            rule_id: 'rule_gross_salary',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'BASIC_SALARY + TOTAL_ALLOWANCES',
            effective_from: '2026-01-01',
            effective_to: '2026-04-30',
            status: 'INACTIVE',
            change_notes: 'Initial production formula using total allowances aggregate',
            created_at: '2026-01-01T00:00:00Z',
          },
          {
            id: 'ver_gross_2',
            rule_id: 'rule_gross_salary',
            version_number: 2,
            version_code: 'v2.0',
            formula_or_query: 'BASIC_SALARY + HOUSING_ALLOWANCE + TRANSPORT_ALLOWANCE + LIVING_ALLOWANCE + OTHER_ALLOWANCES',
            effective_from: '2026-05-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Itemized all four individual allowance variables for granular payroll traceability',
            created_at: '2026-05-01T00:00:00Z',
          },
        ],
      },
      {
        id: 'rule_ss_base',
        code: 'SOCIAL_SECURITY_BASE',
        category: 'SOCIAL_SECURITY',
        name_ar: 'تحديد وعاء اشتراك الضمان الاجتماعي',
        name_en: 'Social Security Base Determination',
        rule_type: 'FORMULA',
        description_ar: 'تطبيق الحدود الدنيا والعليا على أجر الاشتراك الخاضع للضمان',
        description_en: 'Apply minimum and maximum salary thresholds on social security base',
        execution_order: 20,
        output_variable: 'SOCIAL_SECURITY_BASE',
        dependencies: ['GROSS_SALARY'],
        active_version_id: 'ver_ss_base_2',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_ss_base_1',
            rule_id: 'rule_ss_base',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'CLAMP(GROSS_SALARY, SS_MIN_BASE, SS_MAX_BASE)',
            effective_from: '2026-01-01',
            effective_to: '2026-03-31',
            status: 'INACTIVE',
            change_notes: 'Capping formula using CLAMP with dynamic parameters SS_MIN_BASE & SS_MAX_BASE',
            created_at: '2026-01-01T00:00:00Z',
          },
          {
            id: 'ver_ss_base_2',
            rule_id: 'rule_ss_base',
            version_number: 2,
            version_code: 'v2.0',
            formula_or_query: 'MIN(MAX(GROSS_SALARY, SS_MIN_BASE), SS_MAX_BASE)',
            effective_from: '2026-04-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Standardized nested MIN-MAX mathematical expression for cross-platform portability',
            created_at: '2026-04-01T00:00:00Z',
          },
        ],
      },
      {
        id: 'rule_ss_employee',
        code: 'EMPLOYEE_SOCIAL_SECURITY',
        category: 'SOCIAL_SECURITY',
        name_ar: 'حساب استقطاع ضمان الموظف',
        name_en: 'Employee Social Security Contribution',
        rule_type: 'PERCENTAGE',
        description_ar: 'احتساب نسبة استقطاع الموظف من وعاء الضمان المعتمد',
        description_en: 'Calculate employee social security deduction: BASE * (SS_EMPLOYEE_RATE / 100)',
        execution_order: 30,
        output_variable: 'EMPLOYEE_SOCIAL_SECURITY',
        dependencies: ['SOCIAL_SECURITY_BASE'],
        active_version_id: 'ver_ss_emp_2',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_ss_emp_1',
            rule_id: 'rule_ss_employee',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'ROUND(SOCIAL_SECURITY_BASE * (SS_EMPLOYEE_RATE / 100), 2)',
            parameters_json: { base_variable: 'SOCIAL_SECURITY_BASE', rate_parameter: 'SS_EMPLOYEE_RATE' },
            effective_from: '2026-01-01',
            effective_to: '2026-04-30',
            status: 'INACTIVE',
            change_notes: 'Standard employee rate percentage calculation with 2 decimal precision',
            created_at: '2026-01-01T00:00:00Z',
          },
          {
            id: 'ver_ss_emp_2',
            rule_id: 'rule_ss_employee',
            version_number: 2,
            version_code: 'v2.0',
            formula_or_query: 'ROUND(SOCIAL_SECURITY_BASE * (SS_EMPLOYEE_RATE / 100), 0)',
            parameters_json: { base_variable: 'SOCIAL_SECURITY_BASE', rate_parameter: 'SS_EMPLOYEE_RATE' },
            effective_from: '2026-05-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Adjusted rounding precision to integer IQD amounts as requested by finance audit',
            created_at: '2026-05-01T00:00:00Z',
          },
        ],
      },
      {
        id: 'rule_ss_employer',
        code: 'EMPLOYER_SOCIAL_SECURITY',
        category: 'SOCIAL_SECURITY',
        name_ar: 'حساب مساهمة صاحب العمل في الضمان',
        name_en: 'Employer Social Security Contribution',
        rule_type: 'PERCENTAGE',
        description_ar: 'احتساب نسبة جهة العمل المدفوعة لصندوق الضمان الاجتماعي',
        description_en: 'Calculate employer legal share: BASE * (SS_EMPLOYER_RATE / 100)',
        execution_order: 40,
        output_variable: 'EMPLOYER_SOCIAL_SECURITY',
        dependencies: ['SOCIAL_SECURITY_BASE'],
        active_version_id: 'ver_ss_empr_1',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_ss_empr_1',
            rule_id: 'rule_ss_employer',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'ROUND(SOCIAL_SECURITY_BASE * (SS_EMPLOYER_RATE / 100), 2)',
            parameters_json: { base_variable: 'SOCIAL_SECURITY_BASE', rate_parameter: 'SS_EMPLOYER_RATE' },
            effective_from: '2026-01-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Employer contribution calculation according to labor regulations',
            created_at: '2026-01-01T00:00:00Z',
          },
        ],
      },
      {
        id: 'rule_tax_exemptions',
        code: 'TAX_EXEMPTION',
        category: 'EXEMPTION',
        name_ar: 'حساب الإعفاءات الضريبية القانونية',
        name_en: 'Tax Relief & Statutory Exemptions',
        rule_type: 'FORMULA',
        description_ar: 'مجموع الإعفاء الشخصي + إعفاء الزوجة + إعفاء المعالين + استقطاع الضمان',
        description_en: 'Total allowable tax exemptions: Personal + Spouse (if applicable) + (Dependents * ChildExemption) + Employee SS',
        execution_order: 50,
        output_variable: 'TAX_EXEMPTION',
        dependencies: ['DEPENDENTS_COUNT', 'EMPLOYEE_SOCIAL_SECURITY'],
        active_version_id: 'ver_exemp_1',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_exemp_1',
            rule_id: 'rule_tax_exemptions',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'TAX_PERSONAL_EXEMPTION_MONTHLY + (DEPENDENTS_COUNT * TAX_DEPENDENT_EXEMPTION_MONTHLY) + EMPLOYEE_SOCIAL_SECURITY',
            effective_from: '2026-01-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Comprehensive formula combining personal, dependents, and social security exemptions',
            created_at: '2026-01-01T00:00:00Z',
          },
        ],
      },
      {
        id: 'rule_taxable_income',
        code: 'TAXABLE_INCOME',
        category: 'INCOME_TAX',
        name_ar: 'احتساب الدخل الصافي الخاضع للضريبة',
        name_en: 'Taxable Income Computation',
        rule_type: 'FORMULA',
        description_ar: 'طرح الإعفاءات والاستقطاعات من الراتب الإجمالي مع ضمان عدم وجود سالب',
        description_en: 'Compute net taxable income: MAX(0, GROSS_SALARY - TAX_EXEMPTION)',
        execution_order: 60,
        output_variable: 'TAXABLE_INCOME',
        dependencies: ['GROSS_SALARY', 'TAX_EXEMPTION'],
        active_version_id: 'ver_taxable_1',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_taxable_1',
            rule_id: 'rule_taxable_income',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'MAX(0, GROSS_SALARY - TAX_EXEMPTION)',
            effective_from: '2026-01-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Safeguarded formula returning 0 if exemptions exceed gross salary',
            created_at: '2026-01-01T00:00:00Z',
          },
        ],
      },
      {
        id: 'rule_income_tax',
        code: 'TAX_AMOUNT',
        category: 'INCOME_TAX',
        name_ar: 'حساب ضريبة الدخل التصاعدية بالشرائح',
        name_en: 'Progressive Income Tax Bracket Calculation',
        rule_type: 'PROGRESSIVE_TAX',
        description_ar: 'تطبيق شرائح ضريبة الدخل التصاعدية المخزنة في tax_brackets على TAXABLE_INCOME',
        description_en: 'Iterate through active tax brackets and compute marginal progressive tax sum',
        execution_order: 70,
        output_variable: 'TAX_AMOUNT',
        dependencies: ['TAXABLE_INCOME'],
        active_version_id: 'ver_tax_1',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_tax_1',
            rule_id: 'rule_income_tax',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'PROGRESSIVE_BRACKETS(TAXABLE_INCOME, tax_brackets)',
            effective_from: '2026-01-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Standard 4-tier progressive tax brackets engine',
            created_at: '2026-01-01T00:00:00Z',
          },
        ],
      },
      {
        id: 'rule_total_deductions',
        code: 'TOTAL_DEDUCTIONS',
        category: 'GENERAL_PAYROLL',
        name_ar: 'حساب إجمالي الاستقطاعات',
        name_en: 'Total Payroll Deductions',
        rule_type: 'FORMULA',
        description_ar: 'مجموع استقطاع ضمان الموظف وضريبة الدخل',
        description_en: 'Sum of employee social security + income tax',
        execution_order: 80,
        output_variable: 'TOTAL_DEDUCTIONS',
        dependencies: ['EMPLOYEE_SOCIAL_SECURITY', 'TAX_AMOUNT'],
        active_version_id: 'ver_deduct_1',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_deduct_1',
            rule_id: 'rule_total_deductions',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'EMPLOYEE_SOCIAL_SECURITY + TAX_AMOUNT',
            effective_from: '2026-01-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Combines statutory deductions into single aggregate for payroll line items',
            created_at: '2026-01-01T00:00:00Z',
          },
        ],
      },
      {
        id: 'rule_net_salary',
        code: 'NET_SALARY',
        category: 'GENERAL_PAYROLL',
        name_ar: 'احتساب صافي الراتب المستحق',
        name_en: 'Net Payable Salary Calculation',
        rule_type: 'FORMULA',
        description_ar: 'الراتب الإجمالي مطروحاً منه إجمالي الاستقطاعات',
        description_en: 'Compute take-home net salary: GROSS_SALARY - TOTAL_DEDUCTIONS',
        execution_order: 90,
        output_variable: 'NET_SALARY',
        dependencies: ['GROSS_SALARY', 'TOTAL_DEDUCTIONS'],
        active_version_id: 'ver_net_1',
        status: 'ACTIVE',
        effective_from: '2026-01-01',
        effective_to: null,
        versions: [
          {
            id: 'ver_net_1',
            rule_id: 'rule_net_salary',
            version_number: 1,
            version_code: 'v1.0',
            formula_or_query: 'GROSS_SALARY - TOTAL_DEDUCTIONS',
            effective_from: '2026-01-01',
            effective_to: null,
            status: 'ACTIVE',
            change_notes: 'Final net payout formula disbursed to employee accounts',
            created_at: '2026-01-01T00:00:00Z',
          },
        ],
      },
    ];

    // 5. Mock HR Master Data (Simulating the HR Management System integration bridge)
    this.departments = [
      { id: 'dept_it', name_ar: 'تكنولوجيا المعلومات والبرمجيات', name_en: 'Information Technology', code: 'IT', employee_count: 4 },
      { id: 'dept_eng', name_ar: 'الهندسة والمشاريع', name_en: 'Engineering & Projects', code: 'ENG', employee_count: 3 },
      { id: 'dept_fin', name_ar: 'المالية والمحاسبة', name_en: 'Finance & Accounting', code: 'FIN', employee_count: 3 },
      { id: 'dept_hr', name_ar: 'الموارد البشرية والإدارة', name_en: 'Human Resources', code: 'HR', employee_count: 2 },
    ];

    this.branches = [
      { id: 'branch_bgd', name_ar: 'فرع بغداد الرئيسي - المنصور', name_en: 'Baghdad Main Branch - Mansour', code: 'BGD', city: 'Baghdad' },
      { id: 'branch_bsr', name_ar: 'فرع البصرة الإقليمي - الموفقية', name_en: 'Basra Regional Branch', code: 'BSR', city: 'Basra' },
      { id: 'branch_erbl', name_ar: 'فرع أربيل - عينكاوة', name_en: 'Erbil Branch', code: 'ERB', city: 'Erbil' },
    ];

    this.employees = [
      {
        id: 'emp_101',
        employee_number: 'EMP-0101',
        name_ar: 'أحمد جاسم كريم',
        name_en: 'Ahmed Jassim Kareem',
        department_id: 'dept_it',
        department_name_ar: 'تكنولوجيا المعلومات والبرمجيات',
        department_name_en: 'Information Technology',
        branch_id: 'branch_bgd',
        branch_name_ar: 'فرع بغداد الرئيسي',
        branch_name_en: 'Baghdad Main Branch',
        position_ar: 'كبير مهندسي البرمجيات',
        position_en: 'Senior Software Engineer',
        basic_salary: 1800000,
        housing_allowance: 350000,
        transport_allowance: 150000,
        living_allowance: 100000,
        other_allowances: 0,
        gross_salary: 2400000,
        dependents_count: 3,
        marital_status: 'MARRIED_WITH_DEPENDENTS',
        is_resident: true,
        contract_type: 'PERMANENT',
        hire_date: '2022-03-15',
        is_active: true,
      },
      {
        id: 'emp_102',
        employee_number: 'EMP-0102',
        name_ar: 'زينب علي حسن',
        name_en: 'Zainab Ali Hassan',
        department_id: 'dept_fin',
        department_name_ar: 'المالية والمحاسبة',
        department_name_en: 'Finance & Accounting',
        branch_id: 'branch_bgd',
        branch_name_ar: 'فرع بغداد الرئيسي',
        branch_name_en: 'Baghdad Main Branch',
        position_ar: 'مدير تدقيق مالي أول',
        position_en: 'Senior Financial Auditor',
        basic_salary: 2200000,
        housing_allowance: 400000,
        transport_allowance: 200000,
        living_allowance: 100000,
        other_allowances: 100000,
        gross_salary: 3000000,
        dependents_count: 2,
        marital_status: 'MARRIED_WITH_DEPENDENTS',
        is_resident: true,
        contract_type: 'PERMANENT',
        hire_date: '2021-06-01',
        is_active: true,
      },
      {
        id: 'emp_103',
        employee_number: 'EMP-0103',
        name_ar: 'مصطفى حسين الربيعي',
        name_en: 'Mustafa Hussein Al-Rubaie',
        department_id: 'dept_eng',
        department_name_ar: 'الهندسة والمشاريع',
        department_name_en: 'Engineering & Projects',
        branch_id: 'branch_bsr',
        branch_name_ar: 'فرع البصرة الإقليمي',
        branch_name_en: 'Basra Regional Branch',
        position_ar: 'مهندس مواقع ميداني',
        position_en: 'Field Operations Engineer',
        basic_salary: 1400000,
        housing_allowance: 250000,
        transport_allowance: 200000,
        living_allowance: 50000,
        other_allowances: 0,
        gross_salary: 1900000,
        dependents_count: 1,
        marital_status: 'MARRIED',
        is_resident: true,
        contract_type: 'PERMANENT',
        hire_date: '2023-01-10',
        is_active: true,
      },
      {
        id: 'emp_104',
        employee_number: 'EMP-0104',
        name_ar: 'مريم طارق العبيدي',
        name_en: 'Maryam Tariq Al-Obaidi',
        department_id: 'dept_hr',
        department_name_ar: 'الموارد البشرية والإدارة',
        department_name_en: 'Human Resources',
        branch_id: 'branch_bgd',
        branch_name_ar: 'فرع بغداد الرئيسي',
        branch_name_en: 'Baghdad Main Branch',
        position_ar: 'مسؤول علاقات الموظفين والرواتب',
        position_en: 'Payroll & Employee Relations Specialist',
        basic_salary: 1200000,
        housing_allowance: 200000,
        transport_allowance: 100000,
        living_allowance: 50000,
        other_allowances: 0,
        gross_salary: 1550000,
        dependents_count: 0,
        marital_status: 'SINGLE',
        is_resident: true,
        contract_type: 'PERMANENT',
        hire_date: '2024-02-01',
        is_active: true,
      },
      {
        id: 'emp_105',
        employee_number: 'EMP-0105',
        name_ar: 'عمر خالد السعدون',
        name_en: 'Omar Khalid Al-Saadoun',
        department_id: 'dept_it',
        department_name_ar: 'تكنولوجيا المعلومات والبرمجيات',
        department_name_en: 'Information Technology',
        branch_id: 'branch_erbl',
        branch_name_ar: 'فرع أربيل',
        branch_name_en: 'Erbil Branch',
        position_ar: 'أخصائي أمن سيبراني وبنية تحتية',
        position_en: 'Cybersecurity & Infra Specialist',
        basic_salary: 2000000,
        housing_allowance: 350000,
        transport_allowance: 150000,
        living_allowance: 100000,
        other_allowances: 0,
        gross_salary: 2600000,
        dependents_count: 4,
        marital_status: 'MARRIED_WITH_DEPENDENTS',
        is_resident: true,
        contract_type: 'PERMANENT',
        hire_date: '2022-11-20',
        is_active: true,
      },
      {
        id: 'emp_106',
        employee_number: 'EMP-0106',
        name_ar: 'سارة نبيل الخفاجي',
        name_en: 'Sara Nabeel Al-Khafaji',
        department_id: 'dept_fin',
        department_name_ar: 'المالية والمحاسبة',
        department_name_en: 'Finance & Accounting',
        branch_id: 'branch_bgd',
        branch_name_ar: 'فرع بغداد الرئيسي',
        branch_name_en: 'Baghdad Main Branch',
        position_ar: 'محاسب رواتب وتكاليف',
        position_en: 'Payroll & Cost Accountant',
        basic_salary: 950000,
        housing_allowance: 150000,
        transport_allowance: 100000,
        living_allowance: 50000,
        other_allowances: 0,
        gross_salary: 1250000,
        dependents_count: 0,
        marital_status: 'SINGLE',
        is_resident: true,
        contract_type: 'PERMANENT',
        hire_date: '2024-05-15',
        is_active: true,
      },
    ];

    // Seed initial immutable snapshots so reports and dashboard immediately have rich data
    this.seedInitialSnapshots();
  }

  private seedInitialSnapshots() {
    // Generate snapshots for the last 6 months (March 2026 to August 2026)
    const periods = ['2026-03', '2026-04', '2026-05', '2026-06', '2026-07', '2026-08'];
    for (const period of periods) {
      for (const emp of this.employees) {
        const gross = emp.gross_salary;
        const ssBase = Math.min(Math.max(gross, 350000), 5000000);
        const empSS = Math.round(ssBase * 0.05);
        const emprSS = Math.round(ssBase * 0.12);
        const totalSS = empSS + emprSS;

        // Exemptions
        const personalExemp = 208333.33;
        const depExemp = emp.dependents_count * 41666.67;
        const totalExemptions = personalExemp + depExemp + empSS;

        const taxableIncome = Math.max(0, gross - totalExemptions);

        // Progressive tax calculation
        let tax = 0;
        if (taxableIncome > 0) {
          if (taxableIncome <= 250000) {
            tax = taxableIncome * 0.03;
          } else if (taxableIncome <= 500000) {
            tax = 250000 * 0.03 + (taxableIncome - 250000) * 0.05;
          } else if (taxableIncome <= 1000000) {
            tax = 250000 * 0.03 + 250000 * 0.05 + (taxableIncome - 500000) * 0.1;
          } else {
            tax = 250000 * 0.03 + 250000 * 0.05 + 500000 * 0.1 + (taxableIncome - 1000000) * 0.15;
          }
        }
        tax = Math.round(tax);

        const totalDeductions = empSS + tax;
        const netSalary = gross - totalDeductions;

        const snapshot: PayrollCalculationSnapshot = {
          id: `snap_${period}_${emp.id}`,
          employee_id: emp.id,
          employee_name_ar: emp.name_ar,
          employee_name_en: emp.name_en,
          employee_number: emp.employee_number,
          department_id: emp.department_id,
          department_name: emp.department_name_ar,
          branch_id: emp.branch_id,
          branch_name: emp.branch_name_ar,
          payroll_id: `PAYROLL-${period}`,
          payroll_period: period,
          calculation_date: `${period}-28`,
          input_values: {
            basic_salary: emp.basic_salary,
            allowances: {
              housing: emp.housing_allowance,
              transport: emp.transport_allowance,
              living: emp.living_allowance,
              other: emp.other_allowances,
            },
            total_allowances: emp.housing_allowance + emp.transport_allowance + emp.living_allowance + emp.other_allowances,
            gross_salary: gross,
            dependents_count: emp.dependents_count,
            is_resident: emp.is_resident,
            marital_status: emp.marital_status,
            contract_type: emp.contract_type,
          },
          social_security_rule_version_id: 'ver_ss_emp_1',
          tax_rule_version_id: 'ver_tax_1',
          calculation_result: {
            gross_salary: gross,
            social_security_base: ssBase,
            employee_social_security: empSS,
            employer_social_security: emprSS,
            total_social_security: totalSS,
            tax_exemptions: Math.round(totalExemptions),
            taxable_income: Math.round(taxableIncome),
            income_tax: tax,
            total_deductions: totalDeductions,
            net_salary: netSalary,
          },
          step_traces: [
            {
              step_number: 1,
              rule_code: 'GROSS_SALARY',
              rule_name_ar: 'الراتب الإجمالي',
              rule_name_en: 'Gross Salary',
              rule_type: 'FORMULA',
              version_number: 1,
              input_variables: { BASIC_SALARY: emp.basic_salary, TOTAL_ALLOWANCES: gross - emp.basic_salary },
              formula_or_query: 'BASIC_SALARY + TOTAL_ALLOWANCES',
              calculated_value: gross,
              output_variable: 'GROSS_SALARY',
              explanation_ar: `الراتب الأساسي (${emp.basic_salary.toLocaleString()}) + البدلات (${(gross - emp.basic_salary).toLocaleString()}) = ${gross.toLocaleString()}`,
              explanation_en: `Basic (${emp.basic_salary.toLocaleString()}) + Allowances (${(gross - emp.basic_salary).toLocaleString()}) = ${gross.toLocaleString()}`,
            },
            {
              step_number: 2,
              rule_code: 'SOCIAL_SECURITY_BASE',
              rule_name_ar: 'وعاء اشتراك الضمان',
              rule_name_en: 'Social Security Base',
              rule_type: 'FORMULA',
              version_number: 1,
              input_variables: { GROSS_SALARY: gross, SS_MIN_BASE: 350000, SS_MAX_BASE: 5000000 },
              formula_or_query: 'CLAMP(GROSS_SALARY, SS_MIN_BASE, SS_MAX_BASE)',
              calculated_value: ssBase,
              output_variable: 'SOCIAL_SECURITY_BASE',
              explanation_ar: `تطبيق الحدود (الأدنى: 350,000 والأعلى: 5,000,000) -> وعاء الاشتراك: ${ssBase.toLocaleString()}`,
              explanation_en: `Applied threshold caps (Min: 350,000 and Max: 5,000,000) -> Base: ${ssBase.toLocaleString()}`,
            },
            {
              step_number: 3,
              rule_code: 'EMPLOYEE_SOCIAL_SECURITY',
              rule_name_ar: 'استقطاع ضمان الموظف',
              rule_name_en: 'Employee SS Contribution',
              rule_type: 'PERCENTAGE',
              version_number: 1,
              input_variables: { SOCIAL_SECURITY_BASE: ssBase, SS_EMPLOYEE_RATE: 5 },
              formula_or_query: 'SOCIAL_SECURITY_BASE * (5 / 100)',
              calculated_value: empSS,
              output_variable: 'EMPLOYEE_SOCIAL_SECURITY',
              explanation_ar: `${ssBase.toLocaleString()} × 5% = ${empSS.toLocaleString()} د.ع`,
              explanation_en: `${ssBase.toLocaleString()} × 5% = ${empSS.toLocaleString()} IQD`,
            },
            {
              step_number: 4,
              rule_code: 'TAXABLE_INCOME',
              rule_name_ar: 'الدخل الخاضع للضريبة',
              rule_name_en: 'Taxable Income Base',
              rule_type: 'FORMULA',
              version_number: 1,
              input_variables: { GROSS_SALARY: gross, TAX_EXEMPTION: Math.round(totalExemptions) },
              formula_or_query: 'MAX(0, GROSS_SALARY - TAX_EXEMPTION)',
              calculated_value: Math.round(taxableIncome),
              output_variable: 'TAXABLE_INCOME',
              explanation_ar: `الإجمالي (${gross.toLocaleString()}) - الإعفاءات (${Math.round(totalExemptions).toLocaleString()}) = ${Math.round(taxableIncome).toLocaleString()} د.ع`,
              explanation_en: `Gross (${gross.toLocaleString()}) - Exemptions (${Math.round(totalExemptions).toLocaleString()}) = ${Math.round(taxableIncome).toLocaleString()} IQD`,
            },
            {
              step_number: 5,
              rule_code: 'TAX_AMOUNT',
              rule_name_ar: 'ضريبة الدخل التصاعدية',
              rule_name_en: 'Progressive Tax Amount',
              rule_type: 'PROGRESSIVE_TAX',
              version_number: 1,
              input_variables: { TAXABLE_INCOME: Math.round(taxableIncome) },
              formula_or_query: 'PROGRESSIVE_BRACKETS(TAXABLE_INCOME, tax_brackets)',
              calculated_value: tax,
              output_variable: 'TAX_AMOUNT',
              explanation_ar: `مجموع الشرائح الضريبية التصاعدية = ${tax.toLocaleString()} د.ع`,
              explanation_en: `Sum of progressive bracket deductions = ${tax.toLocaleString()} IQD`,
            },
            {
              step_number: 6,
              rule_code: 'NET_SALARY',
              rule_name_ar: 'صافي الراتب المستحق',
              rule_name_en: 'Net Payable Salary',
              rule_type: 'FORMULA',
              version_number: 1,
              input_variables: { GROSS_SALARY: gross, TOTAL_DEDUCTIONS: totalDeductions },
              formula_or_query: 'GROSS_SALARY - TOTAL_DEDUCTIONS',
              calculated_value: netSalary,
              output_variable: 'NET_SALARY',
              explanation_ar: `الراتب الإجمالي (${gross.toLocaleString()}) - الاستقطاعات (${totalDeductions.toLocaleString()}) = ${netSalary.toLocaleString()} د.ع`,
              explanation_en: `Gross (${gross.toLocaleString()}) - Deductions (${totalDeductions.toLocaleString()}) = ${netSalary.toLocaleString()} IQD`,
            },
          ],
          created_at: `${period}-28T14:30:00Z`,
          created_by: 'PayrollEngine_HRMS',
          status: 'FINALIZED',
        };

        this.snapshots.push(snapshot);
      }
    }

    // 8. Seed Initial Audit Logs
    this.auditLogs = [
      {
        id: 'audit_init_1',
        event_id: 'evt_init_001',
        timestamp: '2026-08-01T08:00:00.000Z',
        event_type: 'VERSION_ACTIVATED',
        actor: {
          user_id: 'hr_admin_01',
          name: 'HR System Administrator',
          email: 'vitasiraqhr1@gmail.com',
          role: 'PAYROLL_SYSTEM_ADMIN',
          ip_address: '192.168.1.105',
        },
        resource_type: 'RULE_VERSION',
        resource_id: 'ver_ss_emp_1',
        rule_code: 'EMPLOYEE_SOCIAL_SECURITY',
        summary_ar: 'تفعيل إصدار قاعدة استقطاع ضمان الموظف بنسبة 5% رسمياً',
        summary_en: 'Activated Employee Social Security Rule v1.0 (5% statutory rate)',
        previous_state: { status: 'DRAFT', version_number: 1 },
        new_state: { status: 'ACTIVE', version_number: 1, formula_or_query: 'SOCIAL_SECURITY_BASE * (SS_EMPLOYEE_RATE / 100)' },
        diff_summary: [
          { field: 'status', old_value: 'DRAFT', new_value: 'ACTIVE' },
          { field: 'activated_at', old_value: null, new_value: '2026-08-01T08:00:00Z' },
        ],
        json_payload: JSON.stringify(
          {
            event_id: 'evt_init_001',
            rule_code: 'EMPLOYEE_SOCIAL_SECURITY',
            version: 'v1.0',
            action: 'ACTIVATE_VERSION',
            verified_by_dag: true,
          },
          null,
          2
        ),
        checksum: 'sha256_e82b79a1_20260801',
        bridge_sync_status: 'SYNCED_TO_HR_AUDIT_LOG',
        hr_audit_table_id: 'hr_audit_log_90812',
      },
      {
        id: 'audit_init_2',
        event_id: 'evt_init_002',
        timestamp: '2026-08-01T08:15:00.000Z',
        event_type: 'TAX_BRACKET_UPDATED',
        actor: {
          user_id: 'hr_admin_01',
          name: 'HR System Administrator',
          email: 'vitasiraqhr1@gmail.com',
          role: 'PAYROLL_SYSTEM_ADMIN',
          ip_address: '192.168.1.105',
        },
        resource_type: 'TAX_BRACKET',
        resource_id: 'bracket_1',
        rule_code: 'INCOME_TAX_PROGRESSIVE',
        summary_ar: 'تحديث الشريحة الضريبية الأولى (3% حتى 250,000 د.ع)',
        summary_en: 'Configured Tier 1 Income Tax Bracket (3% up to 250,000 IQD)',
        previous_state: { tax_rate: 3.5, max_income: 200000 },
        new_state: { tax_rate: 3.0, max_income: 250000 },
        diff_summary: [
          { field: 'tax_rate', old_value: 3.5, new_value: 3.0 },
          { field: 'max_income', old_value: 200000, new_value: 250000 },
        ],
        json_payload: JSON.stringify(
          {
            bracket_order: 1,
            rate: 3.0,
            range: '0 - 250,000 IQD',
          },
          null,
          2
        ),
        checksum: 'sha256_3fa981c2_20260801',
        bridge_sync_status: 'SYNCED_TO_HR_AUDIT_LOG',
        hr_audit_table_id: 'hr_audit_log_90813',
      },
      {
        id: 'audit_init_3',
        event_id: 'evt_init_003',
        timestamp: '2026-08-05T11:30:00.000Z',
        event_type: 'VARIABLE_CREATED',
        actor: {
          user_id: 'hr_admin_01',
          name: 'HR System Administrator',
          email: 'vitasiraqhr1@gmail.com',
          role: 'PAYROLL_SYSTEM_ADMIN',
          ip_address: '192.168.1.105',
        },
        resource_type: 'SYSTEM_VARIABLE',
        resource_id: 'var_14',
        rule_code: 'SENIORITY_BONUS',
        summary_ar: 'إضافة متغير نظام جديد SENIORITY_BONUS مربوط بجدول بيانات الموظف',
        summary_en: 'Created system variable SENIORITY_BONUS mapped to hr_employees.hire_date',
        previous_state: undefined,
        new_state: {
          code: 'SENIORITY_BONUS',
          source_type: 'EMPLOYEE_PROFILE',
          source_table: 'hr_employees',
          source_column: 'hire_date',
        },
        diff_summary: [
          { field: 'code', old_value: null, new_value: 'SENIORITY_BONUS' },
          { field: 'source_type', old_value: null, new_value: 'EMPLOYEE_PROFILE' },
        ],
        json_payload: JSON.stringify(
          {
            variable_code: 'SENIORITY_BONUS',
            source: 'EMPLOYEE_PROFILE',
            table: 'hr_employees',
          },
          null,
          2
        ),
        checksum: 'sha256_7c10b42f_20260805',
        bridge_sync_status: 'SYNCED_TO_HR_AUDIT_LOG',
        hr_audit_table_id: 'hr_audit_log_90945',
      },
    ];
  }
}

export const db = new InMemoryDB();

