import {
  Department,
  Branch,
  Position,
  Employee,
  CurrentUser,
  BiometricServerSettings,
  RawAttendanceLog,
  AttendanceRecord,
  LeaveType,
  LeaveBalance,
  LeaveRequest,
  EmployeeSchedule,
  PublicHoliday,
  AttendanceCorrectionRequest,
  AttendanceProcessingRules,
  AuditLog,
} from './types';

export const initialDepartments: Department[] = [
  { id: 1, code: 'IT', name_ar: 'تكنولوجيا المعلومات والتحول الرقمي', name_en: 'Information Technology & Digital', manager_id: 2, manager_name_ar: 'زيد الحسيني', manager_name_en: 'Zaid Al-Husseini', active: true },
  { id: 2, code: 'HR', name_ar: 'الموارد البشرية والشؤون الإدارية', name_en: 'Human Resources & Administration', manager_id: 3, manager_name_ar: 'نور البياتي', manager_name_en: 'Noor Al-Bayati', active: true },
  { id: 3, code: 'OPS', name_ar: 'العمليات والفروع', name_en: 'Operations & Branches', manager_id: 4, manager_name_ar: 'عمر الخفاجي', manager_name_en: 'Omar Al-Khafaji', active: true },
  { id: 4, code: 'FIN', name_ar: 'المالية والحسابات', name_en: 'Finance & Accounting', manager_id: 5, manager_name_ar: 'رنا الجبوري', manager_name_en: 'Rana Al-Jubouri', active: true },
  { id: 5, code: 'CRD', name_ar: 'الائتمان والتمويل الأصغر', name_en: 'Credit & Microfinance', manager_id: 6, manager_name_ar: 'حيدر الكرخي', manager_name_en: 'Haidar Al-Karkhi', active: true },
];

export const initialBranches: Branch[] = [
  { id: 1, code: 'HQ-BGD', name_ar: 'الإدارة العامة - بغداد (المنصور)', name_en: 'Headquarters - Baghdad (Mansour)', city: 'Baghdad', is_headquarter: true, active: true },
  { id: 2, code: 'BR-ERB', name_ar: 'فرع أربيل (عينكاوة)', name_en: 'Erbil Branch (Ankawa)', city: 'Erbil', is_headquarter: false, active: true },
  { id: 3, code: 'BR-BSR', name_ar: 'فرع البصرة (الجزائر)', name_en: 'Basra Branch (Al-Jazaer)', city: 'Basra', is_headquarter: false, active: true },
  { id: 4, code: 'BR-NJF', name_ar: 'فرع النجف الأشرف', name_en: 'Najaf Branch', city: 'Najaf', is_headquarter: false, active: true },
  { id: 5, code: 'BR-SUL', name_ar: 'فرع السليمانية', name_en: 'Sulaymaniyah Branch', city: 'Sulaymaniyah', is_headquarter: false, active: true },
];

export const initialPositions: Position[] = [
  { id: 1, code: 'DEV-SR', title_ar: 'مطور برمجيات أول', title_en: 'Senior Software Engineer', grade: 'G7' },
  { id: 2, code: 'IT-DIR', title_ar: 'مدير تكنولوجيا المعلومات', title_en: 'IT Director', grade: 'G10' },
  { id: 3, code: 'HR-OFF', title_ar: 'مسؤول موارد بشرية وعلاقات موظفين', title_en: 'HR Officer & Employee Relations', grade: 'G6' },
  { id: 4, code: 'OPS-MGR', title_ar: 'مدير العمليات المركزية', title_en: 'Operations Manager', grade: 'G9' },
  { id: 5, code: 'LOAN-OFF', title_ar: 'أخصائي قروض وتمويل', title_en: 'Loan & Credit Specialist', grade: 'G5' },
  { id: 6, code: 'SYS-ADM', title_ar: 'مدير أنظمة وشبكات', title_en: 'Systems & Network Admin', grade: 'G8' },
  { id: 7, code: 'ACC-SR', title_ar: 'محاسب أول', title_en: 'Senior Accountant', grade: 'G7' },
];

export const initialEmployees: Employee[] = [
  {
    id: 1,
    employee_number: 'EMP-1001',
    name_ar: 'أحمد سعدي الموسوي',
    name_en: 'Ahmad Al-Saadi',
    email: 'ahmad.saadi@vitasiraq.com',
    phone: '+964 770 123 4567',
    department_id: 1,
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_id: 1,
    position_ar: 'مطور برمجيات أول',
    position_en: 'Senior Software Engineer',
    manager_id: 2,
    manager_name_ar: 'زيد الحسيني',
    manager_name_en: 'Zaid Al-Husseini',
    employment_status: 'active',
    hire_date: '2021-03-15',
    biometric_id: 'BIO-0101',
    schedule_id: 1,
    schedule_name_ar: 'الدوام الإداري العام (08:00 - 16:00)',
    schedule_name_en: 'Standard Office Shift (08:00 - 16:00)',
    active: true,
  },
  {
    id: 2,
    employee_number: 'EMP-1002',
    name_ar: 'زيد الحسيني',
    name_en: 'Zaid Al-Husseini',
    email: 'zaid.husseini@vitasiraq.com',
    phone: '+964 771 987 6543',
    department_id: 1,
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_id: 2,
    position_ar: 'مدير تكنولوجيا المعلومات',
    position_en: 'IT Director',
    manager_id: null,
    manager_name_ar: null,
    manager_name_en: null,
    employment_status: 'active',
    hire_date: '2019-01-10',
    biometric_id: 'BIO-0102',
    schedule_id: 1,
    schedule_name_ar: 'الدوام الإداري العام (08:00 - 16:00)',
    schedule_name_en: 'Standard Office Shift (08:00 - 16:00)',
    active: true,
  },
  {
    id: 3,
    employee_number: 'EMP-1003',
    name_ar: 'نور البياتي',
    name_en: 'Noor Al-Bayati',
    email: 'noor.bayati@vitasiraq.com',
    phone: '+964 780 445 6677',
    department_id: 2,
    department_name_ar: 'الموارد البشرية والشؤون الإدارية',
    department_name_en: 'Human Resources & Administration',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_id: 3,
    position_ar: 'مسؤول موارد بشرية وعلاقات موظفين',
    position_en: 'HR Officer & Employee Relations',
    manager_id: 2,
    manager_name_ar: 'زيد الحسيني',
    manager_name_en: 'Zaid Al-Husseini',
    employment_status: 'active',
    hire_date: '2020-06-01',
    biometric_id: 'BIO-0103',
    schedule_id: 1,
    schedule_name_ar: 'الدوام الإداري العام (08:00 - 16:00)',
    schedule_name_en: 'Standard Office Shift (08:00 - 16:00)',
    active: true,
  },
  {
    id: 4,
    employee_number: 'EMP-1004',
    name_ar: 'عمر الخفاجي',
    name_en: 'Omar Al-Khafaji',
    email: 'omar.khafaji@vitasiraq.com',
    phone: '+964 772 332 1199',
    department_id: 3,
    department_name_ar: 'العمليات والفروع',
    department_name_en: 'Operations & Branches',
    branch_id: 2,
    branch_name_ar: 'فرع أربيل (عينكاوة)',
    branch_name_en: 'Erbil Branch (Ankawa)',
    position_id: 4,
    position_ar: 'مدير العمليات المركزية',
    position_en: 'Operations Manager',
    manager_id: null,
    manager_name_ar: null,
    manager_name_en: null,
    employment_status: 'active',
    hire_date: '2018-09-12',
    biometric_id: 'BIO-0104',
    schedule_id: 1,
    schedule_name_ar: 'الدوام الإداري العام (08:00 - 16:00)',
    schedule_name_en: 'Standard Office Shift (08:00 - 16:00)',
    active: true,
  },
  {
    id: 5,
    employee_number: 'EMP-1005',
    name_ar: 'فاطمة الكرخي',
    name_en: 'Fatima Al-Karkhi',
    email: 'fatima.karkhi@vitasiraq.com',
    phone: '+964 781 556 7788',
    department_id: 5,
    department_name_ar: 'الائتمان والتمويل الأصغر',
    department_name_en: 'Credit & Microfinance',
    branch_id: 3,
    branch_name_ar: 'فرع البصرة (الجزائر)',
    branch_name_en: 'Basra Branch (Al-Jazaer)',
    position_id: 5,
    position_ar: 'أخصائي قروض وتمويل',
    position_en: 'Loan & Credit Specialist',
    manager_id: 2,
    manager_name_ar: 'زيد الحسيني',
    manager_name_en: 'Zaid Al-Husseini',
    employment_status: 'active',
    hire_date: '2022-02-10',
    biometric_id: 'BIO-0105',
    schedule_id: 1,
    schedule_name_ar: 'الدوام الإداري العام (08:00 - 16:00)',
    schedule_name_en: 'Standard Office Shift (08:00 - 16:00)',
    active: true,
  },
  {
    id: 6,
    employee_number: 'EMP-1006',
    name_ar: 'يوسف العزاوي',
    name_en: 'Youssef Al-Azzawi',
    email: 'youssef.azzawi@vitasiraq.com',
    phone: '+964 750 667 8899',
    department_id: 1,
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_id: 6,
    position_ar: 'مدير أنظمة وشبكات',
    position_en: 'Systems & Network Admin',
    manager_id: 2,
    manager_name_ar: 'زيد الحسيني',
    manager_name_en: 'Zaid Al-Husseini',
    employment_status: 'active',
    hire_date: '2021-11-05',
    biometric_id: 'BIO-0106',
    schedule_id: 2,
    schedule_name_ar: 'وردية الدعم والعمليات المسائية',
    schedule_name_en: 'Technical Support Evening Shift',
    active: true,
  },
  {
    id: 7,
    employee_number: 'EMP-1007',
    name_ar: 'سارة الدوري',
    name_en: 'Sara Al-Douri',
    email: 'sara.douri@vitasiraq.com',
    phone: '+964 773 889 0011',
    department_id: 4,
    department_name_ar: 'المالية والحسابات',
    department_name_en: 'Finance & Accounting',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_id: 7,
    position_ar: 'محاسب أول',
    position_en: 'Senior Accountant',
    manager_id: 4,
    manager_name_ar: 'عمر الخفاجي',
    manager_name_en: 'Omar Al-Khafaji',
    employment_status: 'active',
    hire_date: '2020-04-18',
    biometric_id: 'BIO-0107',
    schedule_id: 1,
    schedule_name_ar: 'الدوام الإداري العام (08:00 - 16:00)',
    schedule_name_en: 'Standard Office Shift (08:00 - 16:00)',
    active: true,
  },
];

export const userProfiles: CurrentUser[] = [
  {
    id: 1,
    employee_id: 1,
    employee_number: 'EMP-1001',
    name_ar: 'أحمد سعدي الموسوي',
    name_en: 'Ahmad Al-Saadi',
    email: 'ahmad.saadi@vitasiraq.com',
    role: 'employee',
    role_name_ar: 'موظف (Employee)',
    role_name_en: 'Employee',
    department_id: 1,
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_ar: 'مطور برمجيات أول',
    position_en: 'Senior Software Engineer',
    manager_id: 2,
    manager_name_ar: 'زيد الحسيني',
    manager_name_en: 'Zaid Al-Husseini',
    biometric_id: 'BIO-0101',
    permissions: ['attendance.view', 'timesheets.view', 'leave.apply', 'leave.view_own', 'schedule.view_own', 'attendance.correction'],
  },
  {
    id: 2,
    employee_id: 2,
    employee_number: 'EMP-1002',
    name_ar: 'زيد الحسيني',
    name_en: 'Zaid Al-Husseini',
    email: 'zaid.husseini@vitasiraq.com',
    role: 'manager',
    role_name_ar: 'مدير مباشر (Direct Manager)',
    role_name_en: 'Direct Manager',
    department_id: 1,
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_ar: 'مدير تكنولوجيا المعلومات',
    position_en: 'IT Director',
    manager_id: null,
    manager_name_ar: null,
    manager_name_en: null,
    biometric_id: 'BIO-0102',
    permissions: [
      'attendance.view',
      'timesheets.view',
      'leave.apply',
      'leave.view_own',
      'schedule.view_own',
      'manager_approval.view',
      'manager_approval.approve',
      'manager_approval.reject',
      'leave.approve',
      'leave.reject',
      'attendance.approve',
    ],
  },
  {
    id: 3,
    employee_id: 3,
    employee_number: 'EMP-1003',
    name_ar: 'نور البياتي',
    name_en: 'Noor Al-Bayati',
    email: 'noor.bayati@vitasiraq.com',
    role: 'hr_admin',
    role_name_ar: 'مسؤول الموارد البشرية (HR Officer)',
    role_name_en: 'HR Officer',
    department_id: 2,
    department_name_ar: 'الموارد البشرية والشؤون الإدارية',
    department_name_en: 'Human Resources & Administration',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_ar: 'مسؤول موارد بشرية وعلاقات موظفين',
    position_en: 'HR Officer & Employee Relations',
    manager_id: 2,
    manager_name_ar: 'زيد الحسيني',
    manager_name_en: 'Zaid Al-Husseini',
    biometric_id: 'BIO-0103',
    permissions: [
      'attendance.view',
      'attendance.import',
      'attendance.process',
      'attendance.edit',
      'timesheets.view',
      'timesheets.export',
      'leave.apply',
      'leave.view_own',
      'leave.view_all',
      'leave.approve',
      'leave.manage_types',
      'leave.manage_balances',
      'schedule.view_all',
      'schedule.manage',
      'manager_approval.view',
    ],
  },
  {
    id: 4,
    employee_id: 6,
    employee_number: 'EMP-ADMIN',
    name_ar: 'مدير النظام (System Administrator)',
    name_en: 'System Administrator',
    email: 'admin@vitasiraq.com',
    role: 'system_admin',
    role_name_ar: 'مدير النظام (Super Admin)',
    role_name_en: 'System Admin',
    department_id: 1,
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_id: 1,
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    position_ar: 'مدير أنظمة وشبكات',
    position_en: 'Systems & Network Admin',
    manager_id: null,
    manager_name_ar: null,
    manager_name_en: null,
    biometric_id: 'BIO-0106',
    permissions: ['*'],
  },
];

export const initialBiometricSettings: BiometricServerSettings = {
  id: 1,
  server_name: 'BIOMETRIC-SERVER-HQ',
  host: '192.168.1.100',
  ip_address: '192.168.1.100',
  port: 1433,
  db_name: 'BioStar_Vitas_Logs',
  username: 'biometric_sync_user',
  password: '••••••••••••••••',
  connection_type: 'sql_server',
  is_active: true,
  auto_sync_enabled: true,
  auto_sync_interval_mins: 15,
  last_sync_at: '2026-08-08 08:30:15',
  last_sync_status: 'success',
  last_sync_log: 'Successfully imported 48 punch records with 0 duplicates.',
  total_logs_fetched: 3420,
};

export const initialAttendanceProcessingRules: AttendanceProcessingRules = {
  grace_period_minutes: 10,
  early_leave_grace_minutes: 5,
  overtime_min_minutes: 30,
  missing_punch_penalty_hours: 4,
  auto_deduct_break_if_unpunched: true,
  break_duration_minutes: 45,
  half_day_hours_threshold: 4,
  allow_multiple_punches: true,
  punch_pairing_strategy: 'first_last',
};

export const initialLeaveTypes: LeaveType[] = [
  {
    id: 1,
    code: 'ANNUAL',
    name_ar: 'إجازة اعتيادية / سنوية',
    name_en: 'Annual Leave',
    is_paid: true,
    requires_approval: true,
    requires_attachment: false,
    max_days_per_year: 21,
    allow_hourly_leave: false,
    deduct_from_balance: true,
    include_weekends: false,
    include_holidays: false,
    active: true,
    color_badge: 'bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300 border-blue-200',
  },
  {
    id: 2,
    code: 'SICK',
    name_ar: 'إجازة مرضية (بتقرير طبي)',
    name_en: 'Sick Leave',
    is_paid: true,
    requires_approval: true,
    requires_attachment: true,
    max_days_per_year: 14,
    allow_hourly_leave: false,
    deduct_from_balance: true,
    include_weekends: false,
    include_holidays: false,
    active: true,
    color_badge: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300 border-emerald-200',
  },
  {
    id: 3,
    code: 'EMERGENCY',
    name_ar: 'إجازة اضطرارية / طارئة',
    name_en: 'Emergency Leave',
    is_paid: true,
    requires_approval: true,
    requires_attachment: false,
    max_days_per_year: 3,
    allow_hourly_leave: true,
    deduct_from_balance: true,
    include_weekends: false,
    include_holidays: false,
    active: true,
    color_badge: 'bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300 border-amber-200',
  },
  {
    id: 4,
    code: 'UNPAID',
    name_ar: 'إجازة بدون راتب',
    name_en: 'Unpaid Leave',
    is_paid: false,
    requires_approval: true,
    requires_attachment: false,
    max_days_per_year: 60,
    allow_hourly_leave: false,
    deduct_from_balance: false,
    include_weekends: true,
    include_holidays: true,
    active: true,
    color_badge: 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-300 border-slate-200',
  },
  {
    id: 5,
    code: 'MATERNITY',
    name_ar: 'إجازة أمومة ورعاية طفل',
    name_en: 'Maternity Leave',
    is_paid: true,
    requires_approval: true,
    requires_attachment: true,
    max_days_per_year: 72,
    allow_hourly_leave: false,
    deduct_from_balance: false,
    include_weekends: true,
    include_holidays: true,
    active: true,
    color_badge: 'bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300 border-purple-200',
  },
  {
    id: 6,
    code: 'OFFICIAL',
    name_ar: 'إجازة رسمية / إيفاد عمل',
    name_en: 'Official Duty / Mission',
    is_paid: true,
    requires_approval: true,
    requires_attachment: true,
    max_days_per_year: 30,
    allow_hourly_leave: true,
    deduct_from_balance: false,
    include_weekends: false,
    include_holidays: false,
    active: true,
    color_badge: 'bg-teal-600 text-white shadow-md dark:bg-teal-900/40 dark:text-white border-teal-200',
  },
];

export const initialLeaveBalances: LeaveBalance[] = [
  { id: 1, employee_id: 1, employee_number: 'EMP-1001', employee_name_ar: 'أحمد سعدي الموسوي', employee_name_en: 'Ahmad Al-Saadi', leave_type_id: 1, leave_type_code: 'ANNUAL', leave_type_name_ar: 'إجازة اعتيادية / سنوية', leave_type_name_en: 'Annual Leave', year: 2026, entitled_days: 21, carried_forward_days: 4, used_days: 5, pending_days: 2, available_days: 18 },
  { id: 2, employee_id: 1, employee_number: 'EMP-1001', employee_name_ar: 'أحمد سعدي الموسوي', employee_name_en: 'Ahmad Al-Saadi', leave_type_id: 2, leave_type_code: 'SICK', leave_type_name_ar: 'إجازة مرضية', leave_type_name_en: 'Sick Leave', year: 2026, entitled_days: 14, carried_forward_days: 0, used_days: 2, pending_days: 0, available_days: 12 },
  { id: 3, employee_id: 1, employee_number: 'EMP-1001', employee_name_ar: 'أحمد سعدي الموسوي', employee_name_en: 'Ahmad Al-Saadi', leave_type_id: 3, leave_type_code: 'EMERGENCY', leave_type_name_ar: 'إجازة اضطرارية', leave_type_name_en: 'Emergency Leave', year: 2026, entitled_days: 3, carried_forward_days: 0, used_days: 1, pending_days: 0, available_days: 2 },
  { id: 4, employee_id: 2, employee_number: 'EMP-1002', employee_name_ar: 'زيد الحسيني', employee_name_en: 'Zaid Al-Husseini', leave_type_id: 1, leave_type_code: 'ANNUAL', leave_type_name_ar: 'إجازة اعتيادية / سنوية', leave_type_name_en: 'Annual Leave', year: 2026, entitled_days: 21, carried_forward_days: 6, used_days: 3, pending_days: 0, available_days: 24 },
  { id: 5, employee_id: 3, employee_number: 'EMP-1003', employee_name_ar: 'نور البياتي', employee_name_en: 'Noor Al-Bayati', leave_type_id: 1, leave_type_code: 'ANNUAL', leave_type_name_ar: 'إجازة اعتيادية / سنوية', leave_type_name_en: 'Annual Leave', year: 2026, entitled_days: 21, carried_forward_days: 2, used_days: 4, pending_days: 0, available_days: 19 },
  { id: 6, employee_id: 5, employee_number: 'EMP-1005', employee_name_ar: 'فاطمة الكرخي', employee_name_en: 'Fatima Al-Karkhi', leave_type_id: 1, leave_type_code: 'ANNUAL', leave_type_name_ar: 'إجازة اعتيادية / سنوية', leave_type_name_en: 'Annual Leave', year: 2026, entitled_days: 21, carried_forward_days: 0, used_days: 6, pending_days: 0, available_days: 15 },
  { id: 7, employee_id: 6, employee_number: 'EMP-1006', employee_name_ar: 'يوسف العزاوي', employee_name_en: 'Youssef Al-Azzawi', leave_type_id: 1, leave_type_code: 'ANNUAL', leave_type_name_ar: 'إجازة اعتيادية / سنوية', leave_type_name_en: 'Annual Leave', year: 2026, entitled_days: 21, carried_forward_days: 1, used_days: 2, pending_days: 0, available_days: 20 },
];

export const initialSchedules: EmployeeSchedule[] = [
  {
    id: 1,
    code: 'SCH-STD-HQ',
    name_ar: 'الدوام الإداري العام (08:00 - 16:00)',
    name_en: 'Standard Office Shift (08:00 - 16:00)',
    schedule_type: 'fixed',
    default_start_time: '08:00',
    default_end_time: '16:00',
    grace_period_minutes: 10,
    early_leave_tolerance_minutes: 5,
    break_duration_minutes: 45,
    weekend_days: ['friday', 'saturday'],
    days_config: [
      { day_of_week: 'sunday', day_name_ar: 'الأحد', day_name_en: 'Sunday', is_working_day: true, start_time: '08:00', end_time: '16:00', break_start: '12:15', break_end: '13:00', required_hours: 8 },
      { day_of_week: 'monday', day_name_ar: 'الإثنين', day_name_en: 'Monday', is_working_day: true, start_time: '08:00', end_time: '16:00', break_start: '12:15', break_end: '13:00', required_hours: 8 },
      { day_of_week: 'tuesday', day_name_ar: 'الثلاثاء', day_name_en: 'Tuesday', is_working_day: true, start_time: '08:00', end_time: '16:00', break_start: '12:15', break_end: '13:00', required_hours: 8 },
      { day_of_week: 'wednesday', day_name_ar: 'الأربعاء', day_name_en: 'Wednesday', is_working_day: true, start_time: '08:00', end_time: '16:00', break_start: '12:15', break_end: '13:00', required_hours: 8 },
      { day_of_week: 'thursday', day_name_ar: 'الخميس', day_name_en: 'Thursday', is_working_day: true, start_time: '08:00', end_time: '16:00', break_start: '12:15', break_end: '13:00', required_hours: 8 },
      { day_of_week: 'friday', day_name_ar: 'الجمعة', day_name_en: 'Friday', is_working_day: false, start_time: '00:00', end_time: '00:00', required_hours: 0 },
      { day_of_week: 'saturday', day_name_ar: 'السبت', day_name_en: 'Saturday', is_working_day: false, start_time: '00:00', end_time: '00:00', required_hours: 0 },
    ],
    is_default: true,
    active: true,
  },
  {
    id: 2,
    code: 'SCH-EVN-OPS',
    name_ar: 'وردية الدعم والعمليات المسائية (16:00 - 23:30)',
    name_en: 'Technical Support Evening Shift',
    schedule_type: 'shift',
    default_start_time: '16:00',
    default_end_time: '23:30',
    grace_period_minutes: 15,
    early_leave_tolerance_minutes: 5,
    break_duration_minutes: 30,
    weekend_days: ['friday', 'saturday'],
    days_config: [
      { day_of_week: 'sunday', day_name_ar: 'الأحد', day_name_en: 'Sunday', is_working_day: true, start_time: '16:00', end_time: '23:30', break_start: '19:00', break_end: '19:30', required_hours: 7.5 },
      { day_of_week: 'monday', day_name_ar: 'الإثنين', day_name_en: 'Monday', is_working_day: true, start_time: '16:00', end_time: '23:30', break_start: '19:00', break_end: '19:30', required_hours: 7.5 },
      { day_of_week: 'tuesday', day_name_ar: 'الثلاثاء', day_name_en: 'Tuesday', is_working_day: true, start_time: '16:00', end_time: '23:30', break_start: '19:00', break_end: '19:30', required_hours: 7.5 },
      { day_of_week: 'wednesday', day_name_ar: 'الأربعاء', day_name_en: 'Wednesday', is_working_day: true, start_time: '16:00', end_time: '23:30', break_start: '19:00', break_end: '19:30', required_hours: 7.5 },
      { day_of_week: 'thursday', day_name_ar: 'الخميس', day_name_en: 'Thursday', is_working_day: true, start_time: '16:00', end_time: '23:30', break_start: '19:00', break_end: '19:30', required_hours: 7.5 },
      { day_of_week: 'friday', day_name_ar: 'الجمعة', day_name_en: 'Friday', is_working_day: false, start_time: '00:00', end_time: '00:00', required_hours: 0 },
      { day_of_week: 'saturday', day_name_ar: 'السبت', day_name_en: 'Saturday', is_working_day: false, start_time: '00:00', end_time: '00:00', required_hours: 0 },
    ],
    is_default: false,
    active: true,
  },
];

export const initialPublicHolidays: PublicHoliday[] = [
  { id: 1, name_ar: 'رأس السنة الميلادية', name_en: 'New Year Day', start_date: '2026-01-01', end_date: '2026-01-01', total_days: 1, is_paid: true, recurring_yearly: true, active: true },
  { id: 2, name_ar: 'عيد الجيش العراقي الباسل', name_en: 'Iraqi Army Day', start_date: '2026-01-06', end_date: '2026-01-06', total_days: 1, is_paid: true, recurring_yearly: true, active: true },
  { id: 3, name_ar: 'عيد نوروز القومي', name_en: 'Nowruz Holiday', start_date: '2026-03-21', end_date: '2026-03-21', total_days: 1, is_paid: true, recurring_yearly: true, active: true },
  { id: 4, name_ar: 'عيد الفطر المبارك', name_en: 'Eid Al-Fitr Holidays', start_date: '2026-03-20', end_date: '2026-03-23', total_days: 4, is_paid: true, recurring_yearly: false, active: true },
  { id: 5, name_ar: 'عيد العمال العالمي', name_en: 'Labor Day', start_date: '2026-05-01', end_date: '2026-05-01', total_days: 1, is_paid: true, recurring_yearly: true, active: true },
  { id: 6, name_ar: 'اليوم الوطني لجمهورية العراق', name_en: 'Iraqi National Day', start_date: '2026-10-03', end_date: '2026-10-03', total_days: 1, is_paid: true, recurring_yearly: true, active: true },
];

export const initialRawLogs: RawAttendanceLog[] = [
  { id: 101, device_id: 'ZK-BGD-HQ-01', employee_biometric_id: 'BIO-0101', employee_name_ar: 'أحمد سعدي الموسوي', employee_name_en: 'Ahmad Al-Saadi', employee_number: 'EMP-1001', punch_datetime: '2026-08-08 08:02:14', punch_type: 'check_in', verify_mode: 'fingerprint', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 08:05:00' },
  { id: 102, device_id: 'ZK-BGD-HQ-01', employee_biometric_id: 'BIO-0101', employee_name_ar: 'أحمد سعدي الموسوي', employee_name_en: 'Ahmad Al-Saadi', employee_number: 'EMP-1001', punch_datetime: '2026-08-08 12:15:30', punch_type: 'break_out', verify_mode: 'fingerprint', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 12:20:00' },
  { id: 103, device_id: 'ZK-BGD-HQ-01', employee_biometric_id: 'BIO-0101', employee_name_ar: 'أحمد سعدي الموسوي', employee_name_en: 'Ahmad Al-Saadi', employee_number: 'EMP-1001', punch_datetime: '2026-08-08 13:00:12', punch_type: 'break_in', verify_mode: 'fingerprint', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 13:05:00' },
  { id: 104, device_id: 'ZK-BGD-HQ-01', employee_biometric_id: 'BIO-0101', employee_name_ar: 'أحمد سعدي الموسوي', employee_name_en: 'Ahmad Al-Saadi', employee_number: 'EMP-1001', punch_datetime: '2026-08-08 17:05:44', punch_type: 'check_out', verify_mode: 'fingerprint', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 17:10:00' },

  { id: 105, device_id: 'ZK-BGD-HQ-01', employee_biometric_id: 'BIO-0102', employee_name_ar: 'زيد الحسيني', employee_name_en: 'Zaid Al-Husseini', employee_number: 'EMP-1002', punch_datetime: '2026-08-08 07:55:10', punch_type: 'check_in', verify_mode: 'face', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 08:00:00' },
  { id: 106, device_id: 'ZK-BGD-HQ-01', employee_biometric_id: 'BIO-0102', employee_name_ar: 'زيد الحسيني', employee_name_en: 'Zaid Al-Husseini', employee_number: 'EMP-1002', punch_datetime: '2026-08-08 16:15:22', punch_type: 'check_out', verify_mode: 'face', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 16:20:00' },

  { id: 107, device_id: 'ZK-BGD-HQ-01', employee_biometric_id: 'BIO-0103', employee_name_ar: 'نور البياتي', employee_name_en: 'Noor Al-Bayati', employee_number: 'EMP-1003', punch_datetime: '2026-08-08 08:15:00', punch_type: 'check_in', verify_mode: 'fingerprint', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 08:20:00' },
  { id: 108, device_id: 'ZK-BGD-HQ-01', employee_biometric_id: 'BIO-0103', employee_name_ar: 'نور البياتي', employee_name_en: 'Noor Al-Bayati', employee_number: 'EMP-1003', punch_datetime: '2026-08-08 16:00:05', punch_type: 'check_out', verify_mode: 'fingerprint', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 16:05:00' },

  { id: 109, device_id: 'ZK-ERB-01', employee_biometric_id: 'BIO-0104', employee_name_ar: 'عمر الخفاجي', employee_name_en: 'Omar Al-Khafaji', employee_number: 'EMP-1004', punch_datetime: '2026-08-08 08:00:00', punch_type: 'check_in', verify_mode: 'card', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 08:05:00' },
  { id: 110, device_id: 'ZK-ERB-01', employee_biometric_id: 'BIO-0104', employee_name_ar: 'عمر الخفاجي', employee_name_en: 'Omar Al-Khafaji', employee_number: 'EMP-1004', punch_datetime: '2026-08-08 15:30:10', punch_type: 'check_out', verify_mode: 'card', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 15:35:00' },

  { id: 111, device_id: 'ZK-BSR-01', employee_biometric_id: 'BIO-0105', employee_name_ar: 'فاطمة الكرخي', employee_name_en: 'Fatima Al-Karkhi', employee_number: 'EMP-1005', punch_datetime: '2026-08-08 08:05:22', punch_type: 'check_in', verify_mode: 'fingerprint', sync_batch_id: 'SYNC-20260808-01', is_processed: true, created_at: '2026-08-08 08:10:00' },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: 1,
    employee_id: 1,
    employee_number: 'EMP-1001',
    employee_name_ar: 'أحمد سعدي الموسوي',
    employee_name_en: 'Ahmad Al-Saadi',
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    date: '2026-08-08',
    scheduled_start: '08:00',
    scheduled_end: '16:00',
    first_punch: '08:02',
    last_punch: '17:05',
    punches: [
      { id: 1, punch_time: '08:02:14', punch_type: 'check_in', source: 'biometric', verify_mode: 'fingerprint', is_valid: true },
      { id: 2, punch_time: '12:15:30', punch_type: 'break_out', source: 'biometric', verify_mode: 'fingerprint', is_valid: true },
      { id: 3, punch_time: '13:00:12', punch_type: 'break_in', source: 'biometric', verify_mode: 'fingerprint', is_valid: true },
      { id: 4, punch_time: '17:05:44', punch_type: 'check_out', source: 'biometric', verify_mode: 'fingerprint', is_valid: true },
    ],
    worked_minutes: 543,
    regular_minutes: 480,
    break_minutes: 45,
    late_minutes: 0,
    early_leave_minutes: 0,
    overtime_minutes: 65,
    status: 'present',
    notes: 'Multi-punch interpreted successfully with 45 mins break and 65 mins overtime.',
    is_corrected: false,
    created_at: '2026-08-08 08:05:00',
    updated_at: '2026-08-08 17:10:00',
  },
  {
    id: 2,
    employee_id: 2,
    employee_number: 'EMP-1002',
    employee_name_ar: 'زيد الحسيني',
    employee_name_en: 'Zaid Al-Husseini',
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    date: '2026-08-08',
    scheduled_start: '08:00',
    scheduled_end: '16:00',
    first_punch: '07:55',
    last_punch: '16:15',
    punches: [
      { id: 5, punch_time: '07:55:10', punch_type: 'check_in', source: 'biometric', verify_mode: 'face', is_valid: true },
      { id: 6, punch_time: '16:15:22', punch_type: 'check_out', source: 'biometric', verify_mode: 'face', is_valid: true },
    ],
    worked_minutes: 500,
    regular_minutes: 480,
    break_minutes: 0,
    late_minutes: 0,
    early_leave_minutes: 0,
    overtime_minutes: 15,
    status: 'present',
    notes: 'On time, face recognition verification.',
    is_corrected: false,
    created_at: '2026-08-08 08:00:00',
    updated_at: '2026-08-08 16:20:00',
  },
  {
    id: 3,
    employee_id: 3,
    employee_number: 'EMP-1003',
    employee_name_ar: 'نور البياتي',
    employee_name_en: 'Noor Al-Bayati',
    department_name_ar: 'الموارد البشرية والشؤون الإدارية',
    department_name_en: 'Human Resources & Administration',
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    date: '2026-08-08',
    scheduled_start: '08:00',
    scheduled_end: '16:00',
    first_punch: '08:15',
    last_punch: '16:00',
    punches: [
      { id: 7, punch_time: '08:15:00', punch_type: 'check_in', source: 'biometric', verify_mode: 'fingerprint', is_valid: true },
      { id: 8, punch_time: '16:00:05', punch_type: 'check_out', source: 'biometric', verify_mode: 'fingerprint', is_valid: true },
    ],
    worked_minutes: 465,
    regular_minutes: 480,
    break_minutes: 0,
    late_minutes: 5,
    early_leave_minutes: 0,
    overtime_minutes: 0,
    status: 'late',
    notes: 'Late arrival calculated after 10 min grace period threshold (5 minutes penalty).',
    is_corrected: false,
    created_at: '2026-08-08 08:20:00',
    updated_at: '2026-08-08 16:05:00',
  },
  {
    id: 4,
    employee_id: 4,
    employee_number: 'EMP-1004',
    employee_name_ar: 'عمر الخفاجي',
    employee_name_en: 'Omar Al-Khafaji',
    department_name_ar: 'العمليات والفروع',
    department_name_en: 'Operations & Branches',
    branch_name_ar: 'فرع أربيل (عينكاوة)',
    branch_name_en: 'Erbil Branch (Ankawa)',
    date: '2026-08-08',
    scheduled_start: '08:00',
    scheduled_end: '16:00',
    first_punch: '08:00',
    last_punch: '15:30',
    punches: [
      { id: 9, punch_time: '08:00:00', punch_type: 'check_in', source: 'biometric', verify_mode: 'card', is_valid: true },
      { id: 10, punch_time: '15:30:10', punch_type: 'check_out', source: 'biometric', verify_mode: 'card', is_valid: true },
    ],
    worked_minutes: 450,
    regular_minutes: 480,
    break_minutes: 0,
    late_minutes: 0,
    early_leave_minutes: 30,
    overtime_minutes: 0,
    status: 'early_leave',
    notes: 'Early departure detected at 15:30.',
    is_corrected: false,
    created_at: '2026-08-08 08:05:00',
    updated_at: '2026-08-08 15:35:00',
  },
  {
    id: 5,
    employee_id: 5,
    employee_number: 'EMP-1005',
    employee_name_ar: 'فاطمة الكرخي',
    employee_name_en: 'Fatima Al-Karkhi',
    department_name_ar: 'الائتمان والتمويل الأصغر',
    department_name_en: 'Credit & Microfinance',
    branch_name_ar: 'فرع البصرة (الجزائر)',
    branch_name_en: 'Basra Branch (Al-Jazaer)',
    date: '2026-08-08',
    scheduled_start: '08:00',
    scheduled_end: '16:00',
    first_punch: '08:05',
    last_punch: null,
    punches: [
      { id: 11, punch_time: '08:05:22', punch_type: 'check_in', source: 'biometric', verify_mode: 'fingerprint', is_valid: true },
    ],
    worked_minutes: 240,
    regular_minutes: 480,
    break_minutes: 0,
    late_minutes: 0,
    early_leave_minutes: 0,
    overtime_minutes: 0,
    status: 'missing_punch',
    notes: 'Missing out punch. Employee has pending attendance correction request.',
    is_corrected: false,
    created_at: '2026-08-08 08:10:00',
    updated_at: '2026-08-08 08:10:00',
  },
  {
    id: 6,
    employee_id: 7,
    employee_number: 'EMP-1007',
    employee_name_ar: 'سارة الدوري',
    employee_name_en: 'Sara Al-Douri',
    department_name_ar: 'المالية والحسابات',
    department_name_en: 'Finance & Accounting',
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    date: '2026-08-08',
    scheduled_start: '08:00',
    scheduled_end: '16:00',
    first_punch: null,
    last_punch: null,
    punches: [],
    worked_minutes: 0,
    regular_minutes: 480,
    break_minutes: 0,
    late_minutes: 0,
    early_leave_minutes: 0,
    overtime_minutes: 0,
    status: 'on_leave',
    notes: 'Approved Annual Leave (REQ-2026-0042).',
    is_corrected: false,
    created_at: '2026-08-08 00:00:00',
    updated_at: '2026-08-08 00:00:00',
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: 1,
    request_number: 'LV-2026-0012',
    employee_id: 1,
    employee_number: 'EMP-1001',
    employee_name_ar: 'أحمد سعدي الموسوي',
    employee_name_en: 'Ahmad Al-Saadi',
    department_name_ar: 'تكنولوجيا المعلومات والتحول الرقمي',
    department_name_en: 'Information Technology & Digital',
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    leave_type_id: 1,
    leave_type_code: 'ANNUAL',
    leave_type_name_ar: 'إجازة اعتيادية / سنوية',
    leave_type_name_en: 'Annual Leave',
    start_date: '2026-08-16',
    end_date: '2026-08-18',
    total_days: 3,
    is_hourly: false,
    reason: 'إجازة اعتيادية لظروف عائلية وسفر داخلي قصير.',
    is_emergency: false,
    contact_during_leave: '+964 770 123 4567 (متوفر على الواتساب)',
    current_approver_id: 2,
    current_approver_name_ar: 'زيد الحسيني',
    current_approver_name_en: 'Zaid Al-Husseini',
    status: 'pending_approval',
    approval_history: [
      { id: 1, stage_order: 1, approver_id: 1, approver_name_ar: 'أحمد سعدي الموسوي', approver_name_en: 'Ahmad Al-Saadi', role_name_ar: 'مقدم الطلب', role_name_en: 'Applicant', action: 'approved', comments: 'تم تقديم الطلب والتحقق من توفر الرصيد (18 يوماً متاحاً).', action_at: '2026-08-08 10:15:00' },
      { id: 2, stage_order: 2, approver_id: 2, approver_name_ar: 'زيد الحسيني', approver_name_en: 'Zaid Al-Husseini', role_name_ar: 'المدير المباشر (Direct Manager)', role_name_en: 'Direct Manager', action: 'pending', comments: undefined, action_at: null },
      { id: 3, stage_order: 3, approver_id: 3, approver_name_ar: 'نور البياتي', approver_name_en: 'Noor Al-Bayati', role_name_ar: 'مسؤول الموارد البشرية (HR Final Review)', role_name_en: 'HR Officer', action: 'pending', comments: undefined, action_at: null },
    ],
    created_at: '2026-08-08 10:15:00',
    updated_at: '2026-08-08 10:15:00',
  },
  {
    id: 2,
    request_number: 'LV-2026-0010',
    employee_id: 5,
    employee_number: 'EMP-1005',
    employee_name_ar: 'فاطمة الكرخي',
    employee_name_en: 'Fatima Al-Karkhi',
    department_name_ar: 'الائتمان والتمويل الأصغر',
    department_name_en: 'Credit & Microfinance',
    branch_name_ar: 'فرع البصرة (الجزائر)',
    branch_name_en: 'Basra Branch (Al-Jazaer)',
    leave_type_id: 2,
    leave_type_code: 'SICK',
    leave_type_name_ar: 'إجازة مرضية (بتقرير طبي)',
    leave_type_name_en: 'Sick Leave',
    start_date: '2026-08-09',
    end_date: '2026-08-10',
    total_days: 2,
    is_hourly: false,
    reason: 'وعكة صحية ومراجعة المستشفى التخصصي مع إرفاق التقرير الطبي.',
    attachment_name: 'medical_report_hospital_basra.pdf',
    attachment_url: '#',
    is_emergency: true,
    contact_during_leave: '+964 781 556 7788',
    current_approver_id: 2,
    current_approver_name_ar: 'زيد الحسيني',
    current_approver_name_en: 'Zaid Al-Husseini',
    status: 'pending_approval',
    approval_history: [
      { id: 4, stage_order: 1, approver_id: 5, approver_name_ar: 'فاطمة الكرخي', approver_name_en: 'Fatima Al-Karkhi', role_name_ar: 'مقدم الطلب', role_name_en: 'Applicant', action: 'approved', comments: 'تم إرفاق التقرير الطبي المصدق.', action_at: '2026-08-08 11:30:00' },
      { id: 5, stage_order: 2, approver_id: 2, approver_name_ar: 'زيد الحسيني', approver_name_en: 'Zaid Al-Husseini', role_name_ar: 'المدير المباشر', role_name_en: 'Direct Manager', action: 'pending', comments: undefined, action_at: null },
    ],
    created_at: '2026-08-08 11:30:00',
    updated_at: '2026-08-08 11:30:00',
  },
  {
    id: 3,
    request_number: 'LV-2026-0008',
    employee_id: 7,
    employee_number: 'EMP-1007',
    employee_name_ar: 'سارة الدوري',
    employee_name_en: 'Sara Al-Douri',
    department_name_ar: 'المالية والحسابات',
    department_name_en: 'Finance & Accounting',
    branch_name_ar: 'الإدارة العامة - بغداد (المنصور)',
    branch_name_en: 'Headquarters - Baghdad (Mansour)',
    leave_type_id: 1,
    leave_type_code: 'ANNUAL',
    leave_type_name_ar: 'إجازة اعتيادية / سنوية',
    leave_type_name_en: 'Annual Leave',
    start_date: '2026-08-08',
    end_date: '2026-08-11',
    total_days: 4,
    is_hourly: false,
    reason: 'إجازة سنوية مجدولة مسبقاً بعد إغلاق الحسابات النصف سنوية.',
    is_emergency: false,
    contact_during_leave: '+964 773 889 0011',
    current_approver_id: null,
    status: 'approved',
    manager_comment: 'تمت الموافقة وتم تسليم المهام للمحاسب المناوب.',
    approval_history: [
      { id: 6, stage_order: 1, approver_id: 7, approver_name_ar: 'سارة الدوري', approver_name_en: 'Sara Al-Douri', role_name_ar: 'مقدم الطلب', role_name_en: 'Applicant', action: 'approved', comments: 'تقديم الطلب في الموعد.', action_at: '2026-08-02 09:00:00' },
      { id: 7, stage_order: 2, approver_id: 4, approver_name_ar: 'عمر الخفاجي', approver_name_en: 'Omar Al-Khafaji', role_name_ar: 'المدير المباشر', role_name_en: 'Direct Manager', action: 'approved', comments: 'موافق عليها بعد التحقق من خطة تغطية العمل.', action_at: '2026-08-03 14:20:00' },
      { id: 8, stage_order: 3, approver_id: 3, approver_name_ar: 'نور البياتي', approver_name_en: 'Noor Al-Bayati', role_name_ar: 'الموارد البشرية', role_name_en: 'HR Final Approval', action: 'approved', comments: 'تم خصم 4 أيام من الرصيد السنوي وتحديث سجل الحضور.', action_at: '2026-08-04 10:00:00' },
    ],
    created_at: '2026-08-02 09:00:00',
    updated_at: '2026-08-04 10:00:00',
  },
];

export const initialCorrectionRequests: AttendanceCorrectionRequest[] = [
  {
    id: 1,
    request_number: 'COR-2026-0004',
    employee_id: 5,
    employee_number: 'EMP-1005',
    employee_name_ar: 'فاطمة الكرخي',
    employee_name_en: 'Fatima Al-Karkhi',
    department_name_ar: 'الائتمان والتمويل الأصغر',
    department_name_en: 'Credit & Microfinance',
    attendance_record_id: 5,
    date: '2026-08-08',
    original_in: '08:05:22',
    original_out: null,
    requested_in: '08:05',
    requested_out: '16:00',
    reason: 'تم الانشغال بزيارة ميدانية عاجلة لعميل ائتماني عند موعد الانصراف وتعذر البصم على الجهاز.',
    approver_id: 2,
    approver_name_ar: 'زيد الحسيني',
    approver_name_en: 'Zaid Al-Husseini',
    status: 'pending',
    created_at: '2026-08-08 16:30:00',
    updated_at: '2026-08-08 16:30:00',
  },
];

export const initialAuditLogs: AuditLog[] = [
  { id: 1, user_id: 1, user_name: 'أحمد سعدي الموسوي', action: 'LEAVE_SUBMIT', entity_type: 'leave_requests', entity_id: 'LV-2026-0012', details: 'Submitted 3 days Annual Leave request', ip_address: '192.168.1.45', created_at: '2026-08-08 10:15:00' },
  { id: 2, user_id: 4, user_name: 'النظام الآلي - Sync Service', action: 'BIOMETRIC_SYNC', entity_type: 'attendance_raw_logs', entity_id: 'BATCH-20260808-01', details: 'Automatic sync from 192.168.1.100 imported 48 records', ip_address: '127.0.0.1', created_at: '2026-08-08 08:30:15' },
  { id: 3, user_id: 3, user_name: 'نور البياتي (HR)', action: 'LEAVE_APPROVE_FINAL', entity_type: 'leave_requests', entity_id: 'LV-2026-0008', details: 'Final approval and balance deduction for Sara Al-Douri', ip_address: '192.168.1.22', created_at: '2026-08-04 10:00:00' },
];
